<a href="https://colab.research.google.com/github/srinubandaru/AIML/blob/main/PythonLib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=(["Hello","Bye","Hey"])
print(arr)

['Hello', 'Hai', 'Hey']


In [ ]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr=np.arange(0,10,3)
print(arr)

[0 3 6 9]


In [ ]:
arr=np.arange(0,10,4)
print(arr)

[0 4 8]


In [ ]:
arr=np.random.rand(3,3)
print(arr)

[[0.52929827 0.46782323 0.58422502]
 [0.37094001 0.52181465 0.10084785]
 [0.65791586 0.44966779 0.67649663]]


In [ ]:
arr=np.random.rand(3,3)
print(arr)

[[0.45596734 0.4255828  0.7628864 ]
 [0.23950941 0.16299513 0.1685128 ]
 [0.80797157 0.68149418 0.61601491]]


In [ ]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.full((3,3),17)
print(arr)

[[17 17 17]
 [17 17 17]
 [17 17 17]]


In [ ]:
arr=np.linspace(0,10,4)
print(arr)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
arr=np.linspace(0,10,6)
print(arr)

[ 0.  2.  4.  6.  8. 10.]


**Shapping **

In [ ]:
import numpy as np
arr=np.arange(6)
reshaped=arr.reshape((2,3))
print(reshaped)
reshaped=arr.reshape((3,2))
print(reshaped)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr=np.array([[1,2],[3,4]])
flat=arr.flatten()
print(flat)

arr=np.array([[1,2],[3,4]])
flat=arr.flatten()
print(flat)

[1 2 3 4]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

merged = np.concatenate([arr1, arr2], axis=0)
print(merged)

merged = np.concatenate([arr1, arr2], axis=1)
print(merged)
# axis =0 row-wise (vertical)
# axis=1 column-wise (horizontal)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([[1, 2,3], [4,5,6]])
arr2 = arr1.T
print(arr2)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [ ]:
arr=np.array([1,2,2,3,3,4,4,5])
print(np.unique(arr))



[1 2 3 4 5]


In [ ]:
arr=np.array([5,2,8,1,3,4,])
print(np.sort(arr))


[1 2 3 4 5 8]


In [ ]:
arr=np.array([0,2,0,5,6,0,9])
count=np.count_nonzero(arr)
print(count)


4


In [ ]:
arr=np.array([1,np.nan,2,np.nan,3,4,5])
cleaned=np.nan_to_num(arr,nan=0)
print(cleaned)


[1. 0. 2. 0. 3. 4. 5.]


In [ ]:
arr=np.array([1,np.nan,2,np.nan,3,4,5])
nan_mask=np.isnan(arr)
print(nan_mask)

[False  True False  True False False False]


In [ ]:
arr=np.array([5,2,8,1,3,4,])
new_arr=np.delete(arr,2)
print(new_arr)

[5 2 1 3 4]


In [ ]:
arr=np.array([5,2,8,1,3,4,])
new_arr=np.insert(arr,2,10)
print(new_arr)


[ 5  2 10  8  1  3  4]


**Pandas**

In [12]:
import pandas as pd
df=pd.read_csv("sales.csv")
print(df.head())


         Date     Product Region  Units_Sold  Revenue
0  2025-01-01      Laptop  South           5     5000
1  2025-01-02      Mobile  North          10     8000
2  2025-01-03      Tablet   East           7     3500
3  2025-01-04  Headphones   West          15     1500
4  2025-01-05  Smartwatch  South           8     4000


In [14]:
df=pd.read_table("data.txt",delimiter="\t")
print(df.head())

    Name  Age       City  Salary
0   Ravi   25  Hyderabad   50000
1  Anita   30      Delhi   65000
2   John   28     Mumbai   58000
3  Priya   27    Chennai   62000
4  Arjun   35  Bangalore   72000


In [16]:
df=pd.read_excel("employees.xlsx",sheet_name="Sheet1")
print(df.head())

   Employee_ID          Name Department       City  Salary
0          101    Ravi Kumar      Sales  Hyderabad   50000
1          102  Anita Sharma         HR      Delhi   60000
2          103   John Mathew         IT     Mumbai   75000
3          104   Priya Singh    Finance    Chennai   68000
4          105   Arjun Reddy  Marketing  Bangalore   72000


In [21]:
import sqlite3
import pandas as pd
conn=sqlite3.connect("company.db")
df=pd.read_sql("SELECT * FROM employees",conn)
print(df.head())
conn.close()

   Employee_ID          Name Department       City  Salary
0          101    Ravi Kumar      Sales  Hyderabad   50000
1          102  Anita Sharma         HR      Delhi   60000
2          103   John Mathew         IT     Mumbai   75000
3          104   Priya Singh    Finance    Chennai   68000
4          105   Arjun Reddy  Marketing  Bangalore   72000


In [23]:
data='{"name":["Amit","Sara"],"age":[25,30]}'
df=pd.read_json(data)
print(df.head())

   name  age
0  Amit   25
1  Sara   30


/tmp/ipykernel_1762/2325771397.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_json(data)


In [22]:
url="sample.html"
dfs=pd.read_html(url)
df=dfs[0]
print(df.head())

   Employee_ID          Name Department  Salary
0          101    Ravi Kumar      Sales   50000
1          102  Anita Sharma         HR   60000
2          103   John Mathew         IT   75000
3          104   Priya Singh    Finance   68000


In [25]:
data={
    "Name":["Ravi","Priya","John"],
    "Age":[25,30,28],
    "City":["Hyderabad","Delhi","Mumbai"]
}
df=pd.DataFrame(data)
print(df.head())
#df.to_csv("data.csv",index=False)
#df

    Name  Age       City
0   Ravi   25  Hyderabad
1  Priya   30      Delhi
2   John   28     Mumbai


In [26]:
data={
    "Name":["Ravi","Sita","Amit","Priya","Kiran","Anita"],
    "Age":[25,30,22,28,35,27],
    "Salary":[50000,60000,45000,70000,80000,52000],
    "Department":["HR","IT","A","P","K","A"]
}
df=pd.DataFrame(data)
df

,Name,Age,Salary,Department
0,Ravi,25,50000,HR
1,Sita,30,60000,IT
2,Amit,22,45000,A
3,Priya,28,70000,P
4,Kiran,35,80000,K
5,Anita,27,52000,A
